### ISSUE TITLE
Add proguard hints to documentation of ViewsDSL

### ISSUE THREAD

**Issue by IIIuminator** [LouisCAD/Splitties#158]
I found that when using view with a type argument, e.g. `view<MapView>()` I had to add that class to my proguard file like so
```proguard
-keep public class com.google.android.gms.maps.MapView
-keepclassmembers public class com.google.android.gms.maps.MapView { *; }
```
or the app would crash when creating the view. It's seem to be like that for basically any view that isn't built-in. I had the issue with `MaterialButton`, `CardView`, `MapView` and some views from third-party libraries.

**Comment by LouisCAD** [comment]
Hi, thanks for the report. It's weird because proguard is supposed to not remove view constructors. Are you using R8, or AGP 3.3+?

The best workaround is to use `view(::MapView)`, or write a function named `mapView` that calls it. 

First class support for `MaterialButton`, `CardView` and other widgets from material components will be added soon.

**Comment by IIIuminator** [comment]
> Hi, thanks for the report. It's weird because proguard is supposed to not remove view constructors. Are you using R8, or AGP 3.3+?

It's proguard with AGP 3.2.1. As I'm not using it anywhere else it might just be removing the whole package. No idea though, just found that the aforementioned rules fix the issue

> The best workaround is to use `view(::MapView)`, or write a function named `mapView` that calls it.

Ah yes of course, thanks for the suggestions. That more convenient than adding proguard rules.

> First class support for `MaterialButton`, `CardView` and other widgets from material components will be added soon.

Great!

**Comment by LouisCAD** [comment]
Next 3.0.0 alpha will mark these overloads of `view` as internal (will require the `@InternalSplittiesApi` experimental annotation) to avoid any unintended usage, and I added some documentation on these overloads to redirect to the right ones.

About proguard, that seems to be a bug in it, because the class should still be referenced in the bytecode with its type, so it should be kept, and android rules should keep the constructors. Note that it doesn't happen with types like `TextView` as they are also referenced with their constructor in the ViewFactory.

**Comment by LouisCAD** [comment]
Latest SNAPSHOT version flags this overload of `view` as experimental, includes Material Components first class support (look for the `MaterialComponentsStyles` class), and more.
Documentation update, changelog and release of version 3.0.0-alpha03 will follow later this week.

If you want to speed the release, you can submit one or more documentation PRs based on the `develop` branch after looking at the commits ahead of the `master` branch, and what's left to document regarding new features and the issues.
