### ISSUE TITLE
Color Resources: !!

### ISSUE THREAD

**Issue by Ribesg** [LouisCAD/Splitties#176]
https://github.com/LouisCAD/Splitties/blob/master/resources/src/main/kotlin/splitties/resources/ColorResources.kt#L41

In which case is the `context` `null`? Would it be a better idea to throw a clear error instead of KNPE? Like `throw IllegalStateException("Cannot get color, Fragment's context is null")`

**Comment by LouisCAD** [comment]
Please, use permalink when referencing a line of code because the content of a branch can change (and will change soon FYI).

It is null when the `Fragment` is not attached.
I believe `!!` is okay in that case because when you use `Fragment` in Android, it's general knowledge to know when `context` is available or not. Adding a text message would add a string to the final apk, making it slightly bigger, for not much gain, as the line of code from the stacktrace should be enough to know where the `KotlinNullPointerException` originated from.
