### ISSUE TITLE
Meta artifact containing all the splits

### ISSUE THREAD

**Issue by IIIuminator** [LouisCAD/Splitties#179]
I'm aware that the whole point of this library is that you use the modules you need to keep apk size down. The thing is, when using lots of the splitties like I do in several projects it would be more convenient to be able do add one meta dependency containing all splits. Cleans up the `build.gradle` and with Proguard/R8 everything thats not used it thrown out for release builds anyway.

**Comment by LouisCAD** [comment]
Funny, that's exactly what I was thinking about these days. I also find it cumbersome to deal with all these artifacts in the projects I work on.
I plan to create artifacts for vanilla Android (which would very likely include Coroutines related artifacts), AppCompat-less AndroidX, AppCompat-full AndroidX and Material Components Android. I'm not sure about the naming though.

I'm open to suggestions about this (even if the naming idea is a bit weird, like `splitties-android-needs-more-fun` or `splitties-fan-club`, or plain boring like `splitties-android-all`), and also if you have any idea regarding the artifacts grouping logic.

Also, is there any artifact you don't use because you don't find it useful or don't like its API surface? This will help me sort out the ones that should not be in the grouping artifacts.

**Comment by IIIuminator** [comment]
As to which splits I'm not using, can't really help with that as I haven't actually tried them all or gotten around to implementing it in some project.
Most useful ones I found to be those which require little adaption and just make something quicker to do, e.g. the resources split with `str` etc.
I'd group everything related to Views DSL, everything related to Views/UI except the DSL (Views extensions, dimensions, colors etc.) maybe pre-made components like Material List extra, I find myself using the extensions a lot but so far didn't have use for the latter.
And then one group with behind the scenes stuff e.g. Activities, Fragment, Main Thread/Handler and so on.
Wouldn't necessarily bundle Stetho init with anything, don't see it fit anywhere

**Comment by LouisCAD** [comment]
Here are all the groups I plan to have:
1. **Android base pack**: activities, appctx, bitflags, bundle, collections, dimensions, fragments, fragmentargs, intents, mainhandler, mainthread, material-colors, permissions (new split using coroutines, released in next version, later this week), preferences, resources, systemservices, toast, views, views-coroutines, views-recyclerview, views-selectable & views-selectable-constraintlayout
2. **Android AppCompat** (pack 1, plus alertdialog-appcompat, alertdialog-appcompat-coroutines, views-appcompat, and views-selectable-appcompat)
3. **Android Material Components** (pack 2, plus material-lists, snackbar, views-cardview, views-coroutines-material & views-material)
4. **Android with Views DSL** (pack 1, plus views-dsl, views-dsl-constraintlayout & views-dsl-recyclerview)
5. **Android AppCompat with Views DSL** (pack 2 & 4, plus views-dsl-appcompat
6. **Android Material Components with Views DSL** (pack 3 & 5, plus views-dsl-coordinatorlayout & views-dsl-material)

Notably absents are:
1. `alertdialog` (to avoid confusion in IDE autocomplete if also using alertdialog-appcompat)
2. `arch-lifecycle` (I'd like to split it up and removed overlap with AndroidX KTX artifacts in the future)
3. `arch-room` (because I use SQLDelight instead of Room for databases, and not all apps need Room)
4. `checkedlazy` (I'm not sure it'd be helpful to everyone, so I think it's better to keep it separate)
5. `exceptions` (same as for checkedlazy)
6. `initprovider` (same as for checkedlazy)
7. `lifecycle-coroutines` (because it will overlap with AndroidX Lifecycle KTX and with upcoming fix in R8 then D8 for https://github.com/Kotlin/kotlinx.coroutines/issues/878)
8. `stetho-init` (because should only be used for debug builds, or a subset of those, for those who want to use it)
9. `typesaferecyclerview` (same as for checkedlazy)
10. `views-dsl-ide-preview` (same as for stetho-init)

I'm still not decided on the base name (prefix) of those artifacts. If you have any ideas, please tell me, it can be helpful.

**Comment by IIIuminator** [comment]
how about `splitties{-android}-fun-pack-{$groupname}` :slightly_smiling_face: 
Grouping sounds good to me :+1:

**Comment by LouisCAD** [comment]
The naming will be `splitties-fun-pack-{target-platform}-{group-qualifier}`, so the naming stays consistent when I target more platforms, all starting with `splitties-fun-pack`.

Here are the artifact ids I plan to have:
` splitites-fun-pack-android-base`
` splitites-fun-pack-android-base-with-views-dsl`
` splitites-fun-pack-android-appcompat`
` splitites-fun-pack-android-appcompat-with-views-dsl`
` splitites-fun-pack-android-material-components`
` splitites-fun-pack-android-material-components-with-views-dsl`

If you want to make further suggestions about it, feel free to do so, even if I released a version with this artifact naming scheme in the meantime.

**Comment by LouisCAD** [comment]
Version 3.0.0-alpha05 should be available tomorrow in the day with docs for the grouping artifacts, and for the new permissions split.

All this is already available in the latest dev version (`3.0.0-dev-008` see instructions in README on the develop branch). I need to write the changelog before releasing properly, but I also need to sleep.

**Comment by LouisCAD** [comment]
Finally released! I'll sleep again very soon!

Thank you very much for the suggestion and the help in the naming.

Enjoy the new stuff!
