### ISSUE TITLE
How to use flag 'useCommit ' in Preferences

### ISSUE THREAD

**Issue by JiongBull** [LouisCAD/Splitties#193]
hi, there is no fun could change this flag [useCommit](https://github.com/LouisCAD/Splitties/blob/105a0241a581dcda4ee4ef67c31aaf99f6f16c5d/modules/preferences/src/androidMain/kotlin/splitties/preferences/Preferences.kt#L73).

**Comment by JiongBull** [comment]
My SDK version is 19, it seems that CACHE costs much more than NO CACHE.

![image](https://user-images.githubusercontent.com/4413502/57178914-4dc89f00-6eaa-11e9-8eaa-a76d0594b36e.png)

**Comment by LouisCAD** [comment]
About cache: yes, that's why there's no additional cache in the library. This test was here to make the decision.

About `useCommit`: that's right, I do not make use of it. I'll remove it, and I'll enforce `edit(blocking = true) { … }` is never called on the main thread.

Do you have a real use case for using `commit()` instead of `apply()`?

**Comment by JiongBull** [comment]
Thanks for your reply, about `useCommit`, i have no reason to use `commit`, just think this field is useless in your codes.

**Comment by LouisCAD** [comment]
Yes, it's useless, it's a leftover from when I was designing the API. Thank you for pointing it out, tracked in #194.
