### ISSUE TITLE
Question: Future development?

### ISSUE THREAD

**Issue by gajicm93** [LouisCAD/Splitties#244]
Hi,

I really like this library, and would like to use it in most of my future projects, but I see that there have not been new releases for over a year now, and even dev releases have stopped since February?

So I just wanted to check if you're planning to maintain this library in the future, so I don't end up with most of my projects using a deprecated library, especially for core functionalities like SharedPreferences, etc..?

Thanks!

**Comment by LouisCAD** [comment]
Hi, SharedPreferences is iself going to be deprecated one day as [Google is working on an alternative](https://docs.google.com/document/d/1c2jkPl68XYXbHb-bURTS98d9RSxST-aiOrbA425l0pw/view#), and I'm unsure about how Splitties and apps using it will adapt to this yet.

I've still been working on Splitties, and there's a lot more extensions I want to publish there. I've been slowed down by a bunch of technical issues that affected my productivity when working on the project as I tried to improve it and add multiplatform support, but I'll overcome them in a way or another, and already overcame some of them (like the dependencies update issue in multi-modules projects).

You can expect at least one release this year (hopefully before October), with changes from dev versions at the very least.

**Comment by LouisCAD** [comment]
You can see there's been some commits on the develop branch recently, and #199 (finally) got merged. Hopefully, I'll publish a Kotlin 1.3 compatible release very soon before moving to Kotlin 1.4 which brings welcome improvements for me as a library developer.

**Comment by LouisCAD** [comment]
Hello, there's been a new release (3.0.0-alpha07), where I merged over 600 commits. The release process was quite smooth thanks to some research to improve it.

I think that shows the commitment. I'll publish a Kotlin 1.4 based release soon (important for the styles part of Splitties Views DSL that uses inline classes since 1.3 inline classes are not compatible with 1.4 ones).

I'm closing this issue, but the discussion is still open if you have any questions.
