### ISSUE TITLE
Snackbar not working

### ISSUE THREAD

**Issue by oluwabajio** [LouisCAD/Splitties#245]
I added  this to graddle 
 implementation("com.louiscad.splitties:splitties-snackbar:3.0.0-alpha06")

then calling  snack("") doesnt work.

**Comment by LouisCAD** [comment]
Try with some text instead of an empty string.

**Comment by oluwabajio** [comment]
<img width="696" alt="Screen Shot 2020-08-02 at 2 25 14 PM" src="https://user-images.githubusercontent.com/13810874/89124069-13deb200-d4cc-11ea-853f-864892cf2005.png">

**Comment by oluwabajio** [comment]
Checking your code, i can see its an extension function of CoordinatorLayout. 

Why dont you make snackbar work without coordinatorLayout, as most people dont use coordinatorLayout in their layouts

**Comment by LouisCAD** [comment]
It's an extension of `CoordinatorLayout` because that's the only place where gestures are properly supported. That said, in dev version `3.0.0-dev-056`, it's changed to `View`, so you can give it a try (see dev version setup instructions in README).

BTW, the Snackar is perfectly working as intended, but your code doesn't compile, which is not an issue. Please, be more specific in the issue title next time.
