### ISSUE TITLE
AppCompat factory <provider> affects the whole app behavior

### ISSUE THREAD

**Issue by Miha-x64** [LouisCAD/Splitties#247]
https://github.com/LouisCAD/Splitties/blob/3df895ad88d273eede629733739efe09b63960b9/modules/views-dsl-appcompat/src/androidMain/AndroidManifest.xml#L10

Hello. I've added `splitties-views-dsl-appcompat` and this affected all views on all activities. Every EditText became AppCompatEditText, even within non-AppCompatActivity, losing its appearance and behaviour.

We've talked about theming some time ago on Slack. Well, that's why I don't use implicit themes, implicit injections, implicit initializations :)

**Comment by LouisCAD** [comment]
How is that an issue, and if it's really an issue, please tell why and how you would solve while keeping a way to have that behavior.

**Comment by Miha-x64** [comment]
This is an issue because adding a library wrecks the whole app appearance and behaviour.

Only AppCompatActivities should contain AppCompat views. Some possible solutions:
* call `android.view.LayoutInflater#getFactory2` and delegate view instantiation to it, or
* override `getSystemService` (this must be done by library user), or
* check whether parent context is AppCompatActivity and choose factory depending on this.

**Comment by Miha-x64** [comment]
Controls on non-AppCompat Activities do not receive their style. EditTexts even cannot be interacted with.

**Comment by LouisCAD** [comment]
Following up, @Miha-x64.
Solution 1 is not possible because the exposed API in `LayoutInflater.Factory2` requires a parameter that only xml can provide (`AttributeSet` which is and can only be implemented by `XmlPullParser`).

That said, I found a good solution: checking the current theme in the AppCompat and MDC view factories, and skip if not this kind of theme.

I plan to release it this week with Kotlin 1.4 update (which will require Kotlin 1.4 in host projects).

**Comment by LouisCAD** [comment]
@Miha-x64 Since you're still probably on Kotlin 1.3, you can try the resolution of this issue by using the dev version `3.0.0-dev-079` whose publication is undergoing as I'm writing these lines: https://github.com/LouisCAD/Splitties/actions/runs/235168446

**Comment by LouisCAD** [comment]
The dev version `3.0.0-dev-079` is now available on the dev repo, closing this.
